replicaCount: 1
image:
  repository: obsidiandynamics/kafdrop
  tag: "3.30.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9000
  nodePort: 30900

kafka:
  brokerConnect: "kafka.kafka.svc.cluster.local:9092"
  properties: |
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=PLAIN
  saslJaasConfig: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"user1\" password=\"Pcu0zU6C8A\";" 