image:
  repository: obsidiandynamics/kafdrop
  tag: "4.0.1"
  pullPolicy: IfNotPresent

kafka:
  brokerConnect: kafka.kafka.svc.cluster.local:9092

service:
  type: NodePort
  port: 9000
  nodePort: 30900

ingress:
  enabled: true
  className: nginx
  host: kafdrop.dev3.nemo.ai.kr
  tlsSecret: kafdrop-tls
