# templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ebs-csi-driver-binding
subjects:
  - kind: ServiceAccount
    name: ebs-csi-node-sa
    namespace: kube-system

  - kind: ServiceAccount
    name: ebs-csi-controller-sa
    namespace: kube-system   
    
roleRef:
  kind: ClusterRole
  name: ebs-csi-driver-role
  apiGroup: rbac.authorization.k8s.io