{{- $nsMap := dict }}
{{- range .Values.secrets }}
  {{- if not (hasKey $nsMap .namespace) }}
    {{- $_ := set $nsMap .namespace true }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secretstore
  namespace: {{ .namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ $.Values.projectID }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: {{ $.Values.serviceAccountKey }}
            key: {{ $.Values.serviceAccountKeyFile }}
---
  {{- end }}
{{- end }} 