controller:
  extraArgs:
    - run

  extraVolumes:
    - name: registry-config
      configMap:
        name: argocd-image-updater-registry

  extraVolumeMounts:
    - name: registry-config
      mountPath: /app/config/registries.conf
      subPath: registries.conf

config:
  registriesConfText: |
    registries: 
      - name: aws
        prefix: "084375578827.dkr.ecr.ap-northeast-2.amazonaws.com"
        api_url: "https://084375578827.dkr.ecr.ap-northeast-2.amazonaws.com"
        ping: true
        credentials:
          use_aws_sdk: true

git:
  writeBranch: infra/application
  user:
    name: halfmoon01
    email: onurivit01@gmail.com
  commitMessageTemplate: "Chore: update image to {{ .NewImage }}"
  pgpSign: false

webhook:
  enabled: true
  method: POST
  url: https://discord.com/api/webhooks/1392729701843341313/ppziPHdh0eWfrh29DhEX8f8iOFOKfMvzt9UFnERIYo-lCLeLiNyvg5-xONBZWifFZAaG
  headers:
    Content-Type: application/json
  payload: |
    {
      "content": "🚀 ArgoCD Image Updater\n✅ Application: `{{ .appName }}`\n📦 Image: `{{ .image }}`\n🆕 Tag: `{{ .newTag }}`"
    }

secret:
  create: false
  name: argocd-image-updater-secret

serviceAccount:
  create: true
  name: argocd-image-updater
  annotations:
    eks.amazonaws.com/role-arn: ${role_arn}

image:
  pullSecrets:
    - name: ghcr-secret  # GitHub Container Registry Pull Secret