controller:
  extraArgs:
    - "run"
    - "--registries-conf-path=/app/config/registries.conf"


git:
  writeBranch: infra/image-updater
  user:
    name: halfmoon01
    email: onurivit01@gmail.com
  commitMessageTemplate: "Chore: update image to {{ .NewImage }}"
  pgpSign: false


webhook:
  enabled: true
  method: POST
  url: https://discord.com/api/webhooks/1392729701843341313/ppziPHdh0eWfrh29DhEX8f8iOFOKfMvzt9UFnERIYo-lCLeLiNyvg5-xONBZWifFZAaG
  headers:
    Content-Type: application/json
  payload: |
    {
      "content": "🚀 ArgoCD Image Updater\n✅ Application: `{{ .appName }}`\n📦 Image: `{{ .image }}`\n🆕 Tag: `{{ .newTag }}`"
    }

secret:
  create: false
  name: argocd-image-updater-secret

serviceAccount:
  name: argocd-image-updater

secret:
  name: argocd-image-updater-secret

image:
  repository: docker.io/argoprojlabs/argocd-image-updater
  tag: v0.11.3
