apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: {{ .Values.backend.namespace.name }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::084375578827:role/backend-irsa-role