projectID: nemo-v2
serviceAccountKey: gcp-sa-key
serviceAccountKeyFile: nemo-v2-474f3745006a.json

secrets:
  - name: mysql-secret
    namespace: data
    externalKey: v3-mysql-secret
  - name: redis-secret
    namespace: data
    externalKey: v3-redis-secret 