projectID: nemo-v2
serviceAccountKey: gcp-sa-key
serviceAccountKeyFile: nemo-v2-474f3745006a.json

secrets:
  - name: frontend-secret
    namespace: app
    externalKey: v3-frontend-secret
  - name: backend-secret
    namespace: app
    externalKey: v3-backend-secret 