apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-headless
  labels:
    app: {{ include "zookeeper.name" . }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "zookeeper.name" . }}