apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  serviceName: {{ .Values.service.name }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name  }}
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ZOO_SERVERS
              value: |-
                {{- range $i, $e := until (.Values.replicaCount | int) }}
                server.{{ $i }}={{ $.Values.service.name }}-{{ $i }}.{{ $.Values.service.name }}-headless:2888:3888
                {{- end }}
          command:
            - sh
            - -c
            - |
              export ZOO_MY_ID=$(hostname | awk -F '-' '{print $NF}');
              exec /opt/bitnami/scripts/zookeeper/run.sh
          volumeMounts:
            - name: data
              mountPath: /bitnami/zookeeper
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}