---
# Source: argocd-image-updater/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-registry
  namespace: argocd
data:
  registries.conf: |-

    registries:
      - name: aws
        prefix: "084375578827.dkr.ecr.ap-northeast-2.amazonaws.com"
        api_url: "https://084375578827.dkr.ecr.ap-northeast-2.amazonaws.com"
        ping: true
        credentials:
          username: "{{AWS_ACCESS_KEY_ID}}"
          password: "{{AWS_SECRET_ACCESS_KEY}}"
---
# Source: argocd-image-updater/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
  namespace: default
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/instance: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-image-updater
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-image-updater
        app.kubernetes.io/instance: test
    spec:
      serviceAccountName: argocd-image-updater
      imagePullSecrets:
        - name: ghcr-secret  # GitHub Container Registry Pull Secret
      containers:
        - name: argocd-image-updater
          image: docker.io/argoprojlabs/argocd-image-updater:v0.11.3
          args:
            - run
            - --registries-conf-path=/app/config/registries.conf
          volumeMounts:
            - name: registry-config
              mountPath: /app/config/registries.conf
              subPath: registries.conf
            # ssh 볼륨 mount 필요하면 추가 가능
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-image-updater-secret
                  key: github.token
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: argocd-image-updater-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: argocd-image-updater-secret
                  key: AWS_SECRET_ACCESS_KEY
      volumes:
        - name: registry-config
          configMap:
            name: argocd-image-updater-registry
