---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: {{ .Values.frontend.imagePullSecretName }}
      containers:
        - name: frontend
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          resources:
            requests:
              memory: {{ .Values.frontend.resources.requests.memory }}
              cpu: {{ .Values.frontend.resources.requests.cpu }}
            limits:
              memory: {{ .Values.frontend.resources.limits.memory }}
              cpu: {{ .Values.frontend.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.livenessProbe.httpGet.path }}
              port: {{ .Values.frontend.livenessProbe.httpGet.port }}
            initialDelaySeconds:
              {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.readinessProbe.httpGet.path }}
              port: {{ .Values.frontend.readinessProbe.httpGet.port }}
            initialDelaySeconds:
              {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
          envFrom:
            - secretRef:
                name: {{ .Values.frontend.secret }}