apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: kafka
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/6-nemo-cloud.git
    targetRevision: infra/terraform-setting
    path: v3/helm-charts/kafka
    helm:
      valueFiles:
        - values-prod.yaml
        
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true