{{- range .Values.ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    {{- range $k, $v := .annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- $configSnippets := list }}
    {{- range .paths }}
      {{- if and .annotations .annotations."nginx.ingress.kubernetes.io/configuration-snippet" }}
        {{- $configSnippets = append $configSnippets .annotations."nginx.ingress.kubernetes.io/configuration-snippet" }}
      {{- end }}
    {{- end }}
    {{- if gt (len $configSnippets) 0 }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- range $configSnippets }}
      {{ . | nindent 6 }}
      {{- end }}
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .host }}
      secretName: {{ .tlsSecret }}
  rules:
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
            {{- if .annotations }}
            {{- range $k, $v := .annotations }}
            {{- if ne $k "nginx.ingress.kubernetes.io/configuration-snippet" }}
            {{- end }}
            {{- end }}
            {{- end }}
        {{- end }}
{{- end }}
