services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ../../cloud/v2/envs/db.env  
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nemo-net

  backend:
    build:
      context: ../../backend/backend-service
      dockerfile:  Dockerfile
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
    ports:
      - "8080:8080"
    env_file:
      - ../../cloud/v2/envs/be.env
    networks:
      - nemo-net

  frontend:
    build:
      context: ../../frontend/frontend-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../../cloud/v2/envs/fe.env
    networks:
      - nemo-net

  ai:
    build:
      context: ../../ai/ai-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../../cloud/v2/envs/ai.env
    networks:
      - nemo-net

networks:
  nemo-net:

volumes:
  mysql-data:
