services:

  db:
    container_name: db
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ../../cloud/v2/envs/db.env  
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nemo-net
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    hostname: redis
    env_file:
      - ../../cloud/v2/envs/db.env  
    volumes:
      - redis-data:/data
    networks:
      - nemo-net
    restart: unless-stopped

  redis-exporter:
    image: bitnami/redis-exporter:latest
    container_name: redis-exporter
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    networks:
      - nemo-net
    depends_on:
      - redis

  backend:
    container_name: backend
    image: asia-northeast3-docker.pkg.dev/nemo-v2/registry/backend:dev-latest
    ports:
      - "8080:8080"
    env_file:
      - ../../cloud/v2/envs/backend.dev.env
    networks:
      - nemo-net
    restart: unless-stopped


  frontend:
    container_name: frontend
    image: asia-northeast3-docker.pkg.dev/nemo-v2/registry/frontend:dev-latest
    ports:
      - "3000:3000"
    env_file:
      - ../../cloud/v2/envs/frontend.dev.env
    networks:
      - nemo-net
    restart: unless-stopped

networks:
  nemo-net:

volumes:
  mysql-data:
  redis-data:
