services:

  backend:
    container_name: backend
    image: asia-northeast3-docker.pkg.dev/nemo-v2-prod/registry/backend:prod-latest
    ports:
      - "8080:8080"
    env_file:
      - ../../cloud/v2/envs/backend.prod.env
    networks:
      - nemo-net

  frontend:
    container_name: frontend
    image: asia-northeast3-docker.pkg.dev/nemo-v2-prod/registry/frontend:prod-latest
    ports:
      - "3000:3000"
    env_file:
      - ../../cloud/v2/envs/frontend.prod.env
    networks:
      - nemo-net
  
  ai:
    container_name: ai-prod
    image: asia-northeast3-docker.pkg.dev/nemo-v2-ai-461016/registry/ai:prod-latest
    ports:
      - "8000:8000"
    env_file:
      - ../../cloud/v2/envs/ai.prod.env
    volumes:
      - /home/ubuntu/nemo/cloud/v2/envs/naemo-project-admin-key.json:/app/naemo-project-admin-key.json
    networks:
      - nemo-net
    restart: unless-stopped

networks:
  nemo-net:
