services:
  db:
    container_name: db
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ../../cloud/v2/envs/db.env  
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nemo-net

  backend:
    container_name: backend
    image: asia-northeast3-docker.pkg.dev/nemo-v2/registry/backend:dev-latest
    ports:
      - "8080:8080"
    env_file:
      - ../../cloud/v2/envs/backend.env
    networks:
      - nemo-net

  frontend:
    container_name: frontend
    image: asia-northeast3-docker.pkg.dev/nemo-v2/registry/frontend:dev-latest
    ports:
      - "3000:3000"
    env_file:
      - ../../cloud/v2/envs/frontend.env
    networks:
      - nemo-net

networks:
  nemo-net:

volumes:
  mysql-data:

