config:
  registries:
    - name: gcp
      prefix: asia-northeast3-docker.pkg.dev
      api_url: https://asia-northeast3-docker.pkg.dev
      credentials: /image-updater/.docker/config.json
      default: true

extraEnv:
  - name: DOCKER_CONFIG
    value: /image-updater/.docker/

extraVolumeMounts:
  - name: docker-config
    mountPath: /image-updater/.docker/
extraVolumes:
  - name: docker-config
    secret:
      secretName: gcp-artifact-registry
      items:
        - key: .dockerconfigjson
          path: config.json 