{{- if .Values.loki.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-ingress
  namespace: {{ .Values.loki.namespace | default .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.loki.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.loki.service }}
            port:
              number: {{ .Values.loki.port }}
{{- end }} 