{{- if .Values.prometheus.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: {{ .Values.prometheus.namespace | default .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- if .Values.tlsSecret }}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.tlsSecret }}
  tls:
  - hosts:
    - {{ .Values.prometheus.host }}
    secretName: {{ .Values.tlsSecret }}
  {{- end }}
  rules:
  - host: {{ .Values.prometheus.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.prometheus.service }}
            port:
              number: {{ .Values.prometheus.port }}
{{- end }} 