ingresses:
  - name: main-ingress
    namespace: dev
    host: dev3.nemo.ai.kr
    tlsSecret: dev-nemo-tls
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    paths:
      # Frontend SSR + Healthcheck
      - path: /
        serviceName: frontend
        servicePort: 3000

      - path: /api/healthcheck
        serviceName: frontend
        servicePort: 3000

      # Backend API
      - path: /auth/
        serviceName: backend
        servicePort: 8080

      - path: /api/
        serviceName: backend
        servicePort: 8080

      - path: /swagger-ui/
        serviceName: backend
        servicePort: 8080

      - path: /swagger-resources/
        serviceName: backend
        servicePort: 8080

      - path: /v3/
        serviceName: backend
        servicePort: 8080

      # SSE
      - path: /api/v2/groups/recommendations/chatbot/stream
        serviceName: backend
        servicePort: 8080

      # WebSocket
      - path: /ai/v2/chatbot/
        serviceName: ai-direct
        servicePort: 8000

      # AI API
      - path: /ai/
        serviceName: ai
        servicePort: 8001

# 외부 AI 서버에 직접 연결
externalServices:
  - name: ai
    namespace: ai
    externalIP: 10.30.2.3
    port: 8000
