---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: backend
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
  type: ClusterIP
