---
namespace:
  name: backend

backend:
  imageRegistry: asia-northeast3-docker.pkg.dev/nemo-v2/registry/backend
  image: asia-northeast3-docker.pkg.dev/nemo-v2/registry/backend:latest
  replicas: 3
  imagePullSecretName: gcp-artifact-registry