apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafdrop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/100-hours-a-week/6-nemo-cloud.git'
    path: v3/dev/charts/monitoring/kafdrop
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 