apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secretstore
  namespace: redis
spec:
  provider:
    gcpsm:
      projectID: nemo-v2
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa-key
            key: nemo-v2-474f3745006a.json 