name: Backend CI for prod-v1

on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar -x test

      - name: Upload JAR to Prod Server
        run: |
          echo "${{ secrets.DEV_SSH_KEY }}" > temp_key
          chmod 600 temp_key
          scp -i temp_key -o StrictHostKeyChecking=no ./build/libs/nemo-server-0.0.1-SNAPSHOT.jar \
          ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:~/nemo/backend/jar-backups/
