name: CI - PR Test & Lint
on:
  pull_request:
    branches: [ci-cd/setup-dev-pipeline]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # 코드 가져오기

      # 1. 자바 환경 세팅
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 2. gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew  # gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      # 3. 테스트 실행
#      - name: Run Tests (추후 테스트 코드 추가 시 추가 예정)
#        run: ./gradlew clean test
