apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace.name }}
data:
  # Database Configuration
  DB_URL: mysql.mysql.svc.cluster.local:3306/dev_db
  
  # Redis Configuration
  REDIS_URL: redis.redis.svc.cluster.local
  REDIS_PORT: "6379"
  
  # Application Configuration
  SPRING_PROFILES_ACTIVE: dev
  KAKAO_REDIRECT_URI: https://dev3.nemo.ai.kr/auth/kakao/callback
  
  # AWS S3 Configuration
  BUCKET_NAME: nemo-uploaded-files
  AWS_REGION: ap-northeast-2
  
  # External Services
  AI_SERVICE_URL: http://10.30.2.3:8001
  GROUP_CHATBOT_URI: ws://10.30.2.3:8001/ai/v2/chatbot
  
  # Token Configuration
  ACCESS_TOKEN_EXPIRATION: "3600000"
  REFRESH_TOKEN_EXPIRATION: "1209600000"
  
  # File Upload Configuration
  IMAGE_FILE_BYTE: 10MB
  IMAGE_REQUEST_BYTE: 10MB
  
  # Health Check
  HEALTHCHECK_URL: "http://localhost:8080/actuator/health"
  
  # Registry Configuration
  REGISTRY_URL: asia-northeast3-docker.pkg.dev/nemo-v2/registry
  
  # Sentry Configuration
  # SENTRY_ENV: dev3
  # SENTRY_RELEASE: 2.0.5
  # SENTRY_SAMPLE_RATE: "1.0"
  # SENTRY_SEND_PII: "true" 