---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{.Release.Namespace}}
spec:
  replicas: {{.Values.backend.replicas}}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: {{.Values.backend.imagePullSecretName}}
      containers:
        - name: backend
          image: {{.Values.backend.image}}
          ports:
            - containerPort:8080
          envFrom:
            - secretRef:
                name: backend-secret
