apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace.name }}
  annotations:
    argocd-image-updater.argoproj.io/image.backend: asia-northeast3-docker.pkg.dev/nemo-v2/registry/backend
    argocd-image-updater.argoproj.io/backend.pull-secret: gcp-artifact-registry
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        {{- toYaml .Values.backend.imagePullSecrets | nindent 8 }}
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 8080
          {{- if .Values.backend.resources }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret 