apiVersion: v1
kind: Service
metadata:
  name: ai
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.ai.service.port }}
      targetPort: {{ .Values.ai.service.targetPort }}
  externalIPs:
    - {{ .Values.ai.externalIP }} 