apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.service.name }}
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - port: {{ .Values.zookeeper.service.port }}
      targetPort: {{ .Values.zookeeper.service.port }}
  selector:
    app: {{ .Chart.Name }}zw