apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  serviceName: {{ .Values.zookeeper.service.name }}-headless
  replicas: {{ .Values.zookeeper.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name  }}
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: zookeeper
          image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.zookeeper.service.port }}
          env:
            - name: ZOO_SERVERS
              value: |-
                {{- range $i, $e := until (.Values.zookeeper.replicaCount | int) }}
                server.{{ $i }}={{ $.Values.zookeeper.service.name }}-{{ $i }}.{{ $.Values.zookeeper.service.name }}-headless:2888:3888
                {{- end }}
            - name: ZOO_MY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          volumeMounts:
            - name: data
              mountPath: /bitnami/zookeeper
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.zookeeper.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.zookeeper.persistence.size }}