apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.8.0
    helm:
      values: |
        # 스토리지만 hostpath로 설정, 나머지는 공식 기본값 사용
        server:
          persistentVolume:
            storageClass: hostpath
        alertmanager:
          persistentVolume:
            storageClass: hostpath
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 