apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None  # ✅ Headless
  selector:
    app: redis