apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', 'until nslookup redis-0.redis-headless.redis.svc.cluster.local; do echo waiting; sleep 2; done']
      containers:
        - name: sentinel
          image: redis:7.2
          ports:
            - containerPort: 26379
          volumeMounts:
            - name: config
              mountPath: /etc/redis
              readOnly: true
          command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
      volumes:
        - name: config
          configMap:
            name: sentinel-config
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - redis-sentinel
              topologyKey: topology.kubernetes.io/zone
