apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-start-script
  namespace: {{ .Release.Namespace }}
data:
  start.sh: |
    #!/bin/bash
    NODE_ID=$(hostname | grep -o '[0-9]*')
    export KAFKA_CFG_NODE_ID=$NODE_ID
    exec /opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh