apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    - name: controller
      port: {{ .Values.container.controllerPort }}
      targetPort: {{ .Values.container.controllerPort }}