apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kafka
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - name: kafka
      port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.targetPort }}
    # - name: controller
    #   port: {{ .Values.kafka.container.controllerPort }}
    #   targetPort: {{ .Values.kafka.container.controllerPort }}
    # - name: external
    #   port: {{ .Values.kafka.container.externalPort }}  # 외부 포트 추가
    #   targetPort: {{ .Values.kafka.container.externalPort }}  # 외부 포트 추가



{{- if .Values.kafka.externalAccess.enabled }}
{{- range $i := until (.Values.kafka.replicaCount | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-external-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: kafka
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    statefulset.kubernetes.io/pod-name: kafka-{{ $i }}
  ports:
    - name: external
      port: {{ $.Values.kafka.container.externalPort }}
      targetPort: {{ $.Values.kafka.container.externalPort }}
{{- end }}
{{- end }}