apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_URL
      remoteRef:
        key: backend-env-prod
        property: DB_URL

    - secretKey: USERNAME
      remoteRef:
        key: backend-env-prod
        property: USERNAME

    - secretKey: PASSWORD
      remoteRef:
        key: backend-env-prod
        property: PASSWORD
        
    - secretKey: REDIS_URL
      remoteRef:
        key: backend-env-prod
        property: REDIS_URL
    - secretKey: REDIS_PORT
      remoteRef:
        key: backend-env-prod
        property: REDIS_PORT
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: backend-env-prod
        property: REDIS_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: backend-env-prod
        property: JWT_SECRET
    - secretKey: KAKAO_REST_API_KEY
      remoteRef:
        key: backend-env-prod
        property: KAKAO_REST_API_KEY
    - secretKey: KAKAO_REDIRECT_URI
      remoteRef:
        key: backend-env-prod
        property: KAKAO_REDIRECT_URI
    - secretKey: BUCKET_NAME
      remoteRef:
        key: backend-env-prod
        property: BUCKET_NAME
    - secretKey: CLOUD_AWS_CREDENTIALS_ACCESS_KEY
      remoteRef:
        key: backend-env-prod
        property: CLOUD_AWS_CREDENTIALS_ACCESS_KEY
    - secretKey: CLOUD_AWS_CREDENTIALS_SECRET_KEY
      remoteRef:
        key: backend-env-prod
        property: CLOUD_AWS_CREDENTIALS_SECRET_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: backend-env-prod
        property: AWS_REGION
    - secretKey: AI_SERVICE_URL
      remoteRef:
        key: backend-env-prod
        property: AI_SERVICE_URL
    - secretKey: GROUP_CHATBOT_URI
      remoteRef:
        key: backend-env-prod
        property: GROUP_CHATBOT_URI
    - secretKey: WEBHOOK_CLOUD_URL
      remoteRef:
        key: backend-env-prod
        property: WEBHOOK_CLOUD_URL
    - secretKey: WEBHOOK_BACKEND_URL
      remoteRef:
        key: backend-env-prod
        property: WEBHOOK_BACKEND_URL
    - secretKey: ACCESS_TOKEN_EXPIRATION
      remoteRef:
        key: backend-env-prod
        property: ACCESS_TOKEN_EXPIRATION
    - secretKey: REFRESH_TOKEN_EXPIRATION
      remoteRef:
        key: backend-env-prod
        property: REFRESH_TOKEN_EXPIRATION
    - secretKey: IMAGE_FILE_BYTE
      remoteRef:
        key: backend-env-prod
        property: IMAGE_FILE_BYTE
    - secretKey: IMAGE_REQUEST_BYTE
      remoteRef:
        key: backend-env-prod
        property: IMAGE_REQUEST_BYTE
    - secretKey: REGISTRY_URL
      remoteRef:
        key: backend-env-prod
        property: REGISTRY_URL
    - secretKey: HEALTHCHECK_URL
      remoteRef:
        key: backend-env-prod
        property: HEALTHCHECK_URL
    - secretKey: SENTRY_AUTH_TOKEN
      remoteRef:
        key: backend-env-prod
        property: SENTRY_AUTH_TOKEN
    - secretKey: SENTRY_DSN
      remoteRef:
        key: backend-env-prod
        property: SENTRY_DSN
    - secretKey: SENTRY_ENV
      remoteRef:
        key: backend-env-prod
        property: SENTRY_ENV
    - secretKey: SENTRY_RELEASE
      remoteRef:
        key: backend-env-prod
        property: SENTRY_RELEASE
    - secretKey: SENTRY_SAMPLE_RATE
      remoteRef:
        key: backend-env-prod
        property: SENTRY_SAMPLE_RATE
    - secretKey: SENTRY_SEND_PII
      remoteRef:
        key: backend-env-prod
        property: SENTRY_SEND_PII
    - secretKey: SPRING_PROFILES_ACTIVE
      remoteRef:
        key: backend-env-prod
        property: SPRING_PROFILES_ACTIVE