apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frontend-secret
  namespace: frontend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: frontend-secret
    creationPolicy: Owner
  data:
    - secretKey: NEXT_PUBLIC_API_URL
      remoteRef:
        key: frontend-env-prod
        property: NEXT_PUBLIC_API_URL
    - secretKey: NEXT_PUBLIC_KAKAO_REDIRECT_URI
      remoteRef:
        key: frontend-env-prod
        property: NEXT_PUBLIC_KAKAO_REDIRECT_URI
    - secretKey: NEXT_PUBLIC_GA_ID
      remoteRef:
        key: frontend-env-prod
        property: NEXT_PUBLIC_GA_ID
    - secretKey: WEBHOOK_CLOUD_URL
      remoteRef:
        key: frontend-env-prod
        property: WEBHOOK_CLOUD_URL
    - secretKey: WEBHOOK_FRONTEND_URL
      remoteRef:
        key: frontend-env-prod
        property: WEBHOOK_FRONTEND_URL
    - secretKey: HEALTHCHECK_URL
      remoteRef:
        key: frontend-env-prod
        property: HEALTHCHECK_URL
    - secretKey: REGISTRY_URL
      remoteRef:
        key: frontend-env-prod
        property: REGISTRY_URL
