apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-image-updater-secret     # Deployment에서 참조하는 Secret 이름
    creationPolicy: Owner
  data:
    - secretKey: github.token
      remoteRef:
        key: backend-env-prod
        property: GITHUB_TOKEN