apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-registry
  namespace: argocd
data:
  registries.conf.yaml: |
    registries:
      - name: aws
        prefix: {{ .Values.config.registriesConf.aws.prefix | quote}}
        api_url: {{ .Values.config.registriesConf.aws.api_url | quote}}
        ping: true
        credentials:
          use_aws_sdk: true