apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=084375578827.dkr.ecr.ap-northeast-2.amazonaws.com/backend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/6-nemo-cloud.git
    targetRevision: infra/applications
    path: v3/helm-charts/argocd-updater
    helm:
      valueFiles:
        - values-updater.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true