# backend-argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    #ArgoCD Image Updater가 감시할 이미지 주소 (ECR 리포지토리)
    argocd-image-updater.argoproj.io/image-list: backend=084375578827.dkr.ecr.ap-northeast-2.amazonaws.com/backend
    argocd-image-updater.argoproj.io/update-strategy.backend: latest
    argocd-image-updater.argoproj.io/allow-tags.backend: ^prod-.*
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: infra/image-updater
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/6-nemo-cloud.git
    targetRevision: infra/applications
    path: v3/helm-charts/backend
    helm:
      valueFiles:
        - values-backend.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true