apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentinel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/6-nemo-cloud.git
    targetRevision: infra/application
    path:  v3/helm-charts/sentinel
    helm:
      valueFiles:
        - values-sentinel.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sentinel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true