apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zookeeper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/6-nemo-cloud.git
    targetRevision: infra/applications
    path: v3/helm-charts/zookeeper
    helm:
      valueFiles:
        - values-zookeeper.yaml
        
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka  # 그대로 kafka 네임스페이스
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true