apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.argocd.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.argocd.clusterIssuer }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.argocd.host }}
      secretName: {{ .Values.argocd.tlsSecret }}
  rules:
    - host: {{ .Values.argocd.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.argocd.name }}
                port:
                  number: 443 