apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storageclass
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/100-hours-a-week/6-nemo-cloud.git'
    targetRevision: infra/kubeadm
    path: v3/dev/infra/storageclass
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true 