apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      dnsPolicy: ClusterFirst
      affinity: {{- toYaml .Values.affinity | nindent 8 }}

      initContainers:
        - name: wait-for-redis
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "[Init] Waiting for redis-0 to be ready..."
              until nslookup redis-0.redis-headless.redis.svc.cluster.local > /dev/null 2>&1; do
                echo "Redis not yet available. Retrying..."
                sleep 2
              done
              echo "[Init] Redis DNS resolved!"


      containers:
        - name: sentinel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["redis-server", "/config/sentinel.conf", "--sentinel"]
          ports:
            - containerPort: 26379
          volumeMounts:
            - name: config
              mountPath: /config
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  until nslookup redis-0.redis-headless.redis.svc.cluster.local; do
                    echo "Waiting for redis-0 DNS..."
                    sleep 2
                  done
            failureThreshold: 30
            periodSeconds: 5

      volumes:
        - name: config
          configMap:
            name: sentinel-config