apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.41.4
    helm:
      values: |
        isDefault: true
        auth_enabled: false
        persistence:
          enabled: true
          size: 10Gi
        tableManager:
          retention_deletes_enabled: true
          retention_period: 168h
        grafana-agent:
          enabled: false
        grafana-agent-operator:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
