apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: backend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::084375578827:role/backend-irsa-role  # 실제 IAM Role ARN으로 교체