backend:
  serviceAccount:
    name: backend
  image:
    repository: 084375578827.dkr.ecr.ap-northeast-2.amazonaws.com/backend
    tag: prod-20250714-1752
  replicas: 3
  imagePullSecrets:
    - name: regcred

  # 카프카 내부 접근용 환경변수
  env:
    KAFKA_BOOTSTRAP_SERVERS: "kafka-headless.kafka.svc.cluster.local:9092"
    SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-headless.kafka.svc.cluster.local:9092"