# Node.js 22 base (Alpine 사용 안 함)
FROM node:22

# 작업 디렉토리
WORKDIR /app

# pnpm 설치
RUN corepack enable && corepack prepare pnpm@10.10.0 --activate

# frontend-service로 복사
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

# 개발 포트
EXPOSE 3000

# 개발 서버 실행
CMD ["pnpm", "start"]