apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frontend-secret
  namespace: frontend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secretstore
    kind: SecretStore
  target:
    name: frontend-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: v3-frontend-secret