apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/100-hours-a-week/6-nemo-cloud.git'
    targetRevision: infra/kubeadm
    path: v3/dev/charts/app/backend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  metadata:
    annotations:
      argocd-image-updater.argoproj.io/image-list: backend=asia-northeast3-docker.pkg.dev/nemo-v2/registry/backend
      argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build
      argocd-image-updater.argoproj.io/write-back-method: git 