apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=asia-northeast3-docker.pkg.dev/nemo-v2/registry/frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^dev-[0-9]{8}-[0-9]{4}$
    argocd-image-updater.argoproj.io/frontend.values: image.tag
    argocd-image-updater.argoproj.io/frontend.write-back-method: git
spec:
  project: default
  source:
    repoURL: 'https://github.com/100-hours-a-week/6-nemo-cloud.git'
    targetRevision: infra/kubeadm
    path: v3/dev/charts/app/frontend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 