controller:
  replicaCount: 3
  
  persistence:
    enabled: true
    storageClass: gp2 
    size: 5Gi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: kafka
          topologyKey: topology.kubernetes.io/zone

zookeeper:
  enabled: false

kraft:
  enabled: true
