apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.12.3
    helm:
      parameters:
        - name: "argocd.serverAddress"
          value: "argocd-server.argocd.svc"
        - name: "config.registries[0].name"
          value: "gcp"
        - name: "config.registries[0].prefix"
          value: "asia-northeast3-docker.pkg.dev"
        - name: "config.registries[0].api_url"
          value: "https://asia-northeast3-docker.pkg.dev"
        - name: "config.registries[0].credentials"
          value: "pullsecret:argocd/gcp-artifact-registry"
        - name: "config.registries[0].default"
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 